- name: Copy service configurations & deploy
  hosts: master
  any_errors_fatal: true
  become: true
  roles:
    - role: services/metallb
    - { role: services/glusterfs, when: storage_solution == "glusterfs" }
    - { role: services/geth, when: deploy_geth == true}
    - { role: services/keep-random-beacon, when: deploy_keep_random_beacon == true}
    - { role: services/keep-ecdsa, when: deploy_keep_ecdsa == true}